export const USER_COMMENTS = "USER_COMMENTS";
export const FETCH_DISHES = "FETCH_DISHES";
export const FETCH_DISHES_FAILED = "FETCH_DISHES_FAILED";
export const FETCH_PROMOTION = "FETCH_PROMOTION";
export const FETCH_PROMOTION_FAILED = "FETCH_PROMOTION_FAILED";
export const FETCH_LEADER = "FETCH_LEADER";
export const FETCH_LEADER_FAILED = "FETCH_LEADER_FAILED";
